name: msciproject
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - appdirs=1.4.3
  - asciitree=0.3.3
  - asn1crypto=1.2.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - blas=1.0
  - bokeh=1.4.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cfitsio=3.470
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - colorama=0.4.3
  - configobj=5.0.6
  - cryptography=2.8
  - curl=7.67.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.9.1
  - dask-core=2.9.1
  - distributed=2.9.1
  - docutils=0.15.2
  - expat=2.2.5
  - fasteners=0.15
  - freetype=2.9.1
  - freexl=1.0.5
  - fsspec=0.6.2
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - jinja2=2.10.3
  - jpeg=9c
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libboost=1.67.0
  - libclang=9.0.1
  - libcurl=7.67.0
  - libffi=3.2.1
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libpq=12.1
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - libxslt=1.1.33
  - locket=0.2.0
  - lxml=4.4.2
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - monotonic=1.5
  - more-itertools=8.2.0
  - msgpack-python=0.6.1
  - netcdf4=1.5.3
  - numcodecs=0.6.4
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - owslib=0.18.0
  - packaging=20.0
  - pandas=0.25.3
  - partd=1.1.0
  - pcre=8.43
  - pillow=7.0.0
  - pluggy=0.13.1
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.1
  - proj=6.2.1
  - psutil=5.6.7
  - py=1.8.1
  - pycparser=2.19
  - pyepsg=0.4.0
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyorbital=1.5.0
  - pyparsing=2.4.6
  - pyproj=2.4.2.post1
  - pyqt=5.12.3
  - pyresample=1.13.2
  - pyshp=2.1.0
  - pyside2=5.13.1
  - pysocks=1.7.1
  - pyspectral=0.9.2
  - pytest=5.3.5
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-geotiepoints=1.1.8
  - pytz=2019.3
  - pyyaml=5.2
  - qt=5.12.5
  - rasterio=1.1.2
  - requests=2.22.0
  - satpy=0.17.1
  - scipy=1.3.2
  - setuptools=44.0.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.13.0
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - sqlite=3.30.1
  - tbb=2018.0.5
  - tblib=1.6.0
  - tiledb=1.7.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.40.2
  - trollimage=1.11.0
  - trollsift=0.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - wheel=0.33.6
  - xarray=0.14.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.3.2
  - zict=1.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pip==19.3.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - wget==3.2


