name: msciproject
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.2
  - numpy=1.17.4
  - pandas=0.25.3
  - pyresample=1.13.2
  - pytest=5.3.5
  - python=3.7.6
  - requests=2.22.0
  - satpy=0.17.1
  - scipy=1.3.2


